### ISSUE TITLE
No MEI files are included for testing

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon.js#101]
Because no actual MEI files are included, nothing shows up on index.html. Perhaps this is intentional, but something somewhere should link to the demo files, perhaps in the readme?

**Comment by ATranimal** [comment]
Maybe on Rodan?

**Comment by ahankinson** [comment]
Does https://github.com/DDMAL/Neon.js/blob/master/test/data/allneumes.mei work?

**Comment by ATranimal** [comment]
Sorry, I was unclear in my issue message. The MEI in the folder is there for qunit testing I'm pretty sure, but we were more looking for the MEI files found in the demo at http://neon.simssa.ca/.

I also just realized we can download those files straight from that page..... so going to close this issue.

**Comment by ATranimal** [comment]
Pre-emptively closed, there seems to be no way to access those files from the demo page.

**Comment by ATranimal** [comment]
I accidentally clicked close and comment 👎

**Comment by ahankinson** [comment]
There are thousands of MEI files on Gershwin in the Liber Usualis folders. Ask @vigliensoni to give you access to Gershwin.

**Comment by ATranimal** [comment]
Found MEI files (Both salzinnes and from the demo)
