### ISSUE TITLE
LibMei Error when using the uploading interface to upload MEI files 

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon.js#105]
When uploading mei files on the homepage, the following error occurs:

Traceback (most recent call last):
  File "/Users/andrewtran/Documents/Neon.js/app_env/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: post() takes exactly 1 argument (2 given)

**Comment by ATranimal** [comment]
I fixed the post function here https://github.com/DDMAL/Neon.js/commit/d3329ef41ecc432dc311f9690e513be117358f1c to properly execute when uploading files. There is an issue with validating MEI files now though, maybe @ahankinson can give me some advice?

When uploading an MEI file, there is a try/catch block where it tries the code `mei = XmlImport.documentFromText(contents)`, which throws the exception "That element name layout was not registered with the factory and could not be created." I also tried changing it to `mei = XmlImport.documentFromFile(contents)`, but it returned an error saying the file is malformed. I'm still working on reading through the libmei documentation to understand how the function works but if you have some advice that'd be great!

**Comment by ATranimal** [comment]
Probably going to scrap the validation through the libmei library for now. I tested it on all versions of libmei (1, 2, 3, master) and they all returned the same errors except for libmei 2 which required me to rewrite all the imports because it was organized differently. 

For now, going to just check the file extension as a soft check for mei files and move on.

**Comment by ahankinson** [comment]
libmei also provides read/write for the MEI files, so you'll probably have to deal with it at some point, right?

**Comment by ATranimal** [comment]
Yes, when we work on #114 we'll probably dive deeper into libmei, but for now having quick and correct uploads will help us get to that point faster! (We think so anyways)

**Comment by ATranimal** [comment]
Looked into this issue all day today. Getting the 'That element name layout was not registered with the factory and could not be created.' error meant that the element <layout> was not included in libmei by default. We tried a bunch of compiled odd generating things online based off of the libmei wiki, but they all failed. We eventually ended up adding them by hand, but this is not a feasible option.

We could potentially just add all the missing elements haphazardly but not really sure if thats a great way to do it. The tool in the libmei to generate schemas is really buggy with all the tools that we've tried and fails to compile in xcode.

We found https://github.com/music-encoding/mei-incubator as well, which seemed like it would be helpful, but its deprecated and the code there doesn't work. There might be some sort of modern version of this with a better ODD file for our uses.

**Comment by ahankinson** [comment]
I, and others, have used the parseschema tool for several years and have not found any bugs in it. If you find bugs, please report them or, ideally, fix them.

Have you read this page? https://github.com/DDMAL/libmei/wiki/Understanding-libmei
And this? https://github.com/DDMAL/libmei/wiki/Automatic-Code-Generation

Have you talked to Yaolong about using libmei?

The MEI incubator is VERY old. Avoid. There be dragons.

**Comment by ATranimal** [comment]
Yes, we read them both.

There was no errors in creating modules with parseschema, but using the generated modules in libmei and trying to compile in xcode lead to a lpt of errors. Entirely possible we used a bad compiled odd file, which is why we were looking for premade ones ie mei incubator.

We talked to yaolong and he said hes not sure about adding additional elements to a schema.

**Comment by ahankinson** [comment]
What were the errors? Can you post them? It's difficult to help if I don't know what the problem is.

**Comment by ahankinson** [comment]
I've fixed a couple problems in the XCode project file for plain-old libmei. Could you see if that fixes any of your problems? You should be able to compile it now.

**Comment by ATranimal** [comment]
As a test, we tried manually adding elements into the modules for libmei to see if this would actually fix our problem. Doing this actually made the uploading and saving features of Neon work again.

Now, we just need to learn how to do it properly. We'll try what we did with parseschema2 again with your fixes to xcode and see how that works.

**Comment by ATranimal** [comment]
Just using the libmei-develop version, we're running into errors when running Neon.js. It fails to import the XmlImport class from pymei. Just by looking through libmei-develop, it looks like the implementation of XmlImport is widely different than in libmei-master.

**Comment by ATranimal** [comment]
libmei is also throwing errors on mei files with meiversion 2013
