### ISSUE TITLE
Update Fabric.js

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon.js#120]
Neon uses an old version of Fabric.js so it could be a good idea to update Fabric and make sure everything still works.

**Comment by ATranimal** [comment]
Updated in 7108357498df72a4f6abeec787c64940c80fb304

**Comment by ATranimal** [comment]
we did not actually do this correctly :(

**Comment by ATranimal** [comment]
This is too big of an issue to put into the milestone. This is going to need to be a large ongoing procedure that will be developed aside from everything else. Progress for this will be carried out in fabric-update until all the bugs have been ironed out.

**Comment by ATranimal** [comment]
Might close this and set this as its own milestone
