### ISSUE TITLE
Clefs randomly being created when using the gui

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon.js#127]
After placing a clef on a staff, when switching controls on the side bar, sometimes a random clef gets placed. Not sure why but should be looked into.
![screen shot 2017-05-10 at 12 44 27 pm](https://cloud.githubusercontent.com/assets/13473087/25910472/709cf70e-357e-11e7-90c5-9caa810673ff.png)

**Comment by zoemcl** [comment]
This also happens sometimes with the neumes. Specifically: inserting a clef first, then changing to edit, then going back to insert and selecting clef.

**Comment by ATranimal** [comment]
fixed in d6503bd700d29585880a8b8018dda617364c95d4
