### ISSUE TITLE
Select and Edit

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon.js#142]
Users should be able to select and edit all elements on a staff. This functionality is available for note heads, but not yet for ornaments or barlines.

**Comment by zoemcl** [comment]
This functionality is available for for adding dots but not for episemas yet. Also, when adding a dot, the neume moves towards the right repeatedly. Still needs to implemented for barlines.

**Comment by ATranimal** [comment]
Started work for this in abbdf224756c33a112a5373d557ae963ce39a9ab.

Unlike clef shape and neume shape, there doesn't seem to be a built in function in the division model to allow for division changing. Might have to edit the model itself to allow updating of the division type. (Neumes have setHeadShape() in nc, and setShape() in clef)

**Comment by ATranimal** [comment]
Finished in 7a307f5878bae16338244dfd0694d4bad14b4009

Divisions now work perfectly
