### ISSUE TITLE
Episema Editing

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon.js#145]
Add in the functionality to add in episemas on neumes that have already been inserted

**Comment by zoemcl** [comment]
Fixed in f8f131d

**Comment by zoemcl** [comment]
Just realized that toggling the episemas does not save to the MEI file. Will fix this.

**Comment by ATranimal** [comment]
Looking at the MEI files, there may be an even deeper issue in which the episemas are not being deleted properly when notes are being deleted. It seems that the <neume> <nc> and <note> tags are being deleted, but there are a lot of floating episema files. The entire saving/loading/deleting code of episemas will need to be thoroughly checked to ensure proper functionality.

**Comment by zoemcl** [comment]
fixed in 03f1deb
