### ISSUE TITLE
Updating documentation with all changes upto first milestone

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon.js#152]
For the return of Ichiro, we need to add all the changes that we've made to the documentation.

**Comment by zoemcl** [comment]
Merged all the old wiki pages into a single page and started working on the tutorial page.

**Comment by zoemcl** [comment]
Making another wiki page describing the different type of groupings.

**Comment by zoemcl** [comment]
Documentation is updated to current functionality. Images to come.

**Comment by ATranimal** [comment]
Documentation is pretty much completely updated. Tips will be added as user testing begins
