### ISSUE TITLE
Implement a way to refresh the canvas

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon.js#182]
It would be useful for to implement a way to refresh the canvas without refreshing the entire page. This would be useful for several other functionalities such as correcting OMR MEI files and the way we are implementing our undo functionality.

**Comment by zoemcl** [comment]
This seems more difficult than anticipated and is no longer required for the undo functionality do I simply added a refresh button which refreshes the entire page in ee098ad

**Comment by zoemcl** [comment]
Working on this again since it might be the only way to get undo to work.

**Comment by ATranimal** [comment]
Complete done in 74cd397
