### ISSUE TITLE
Comment out cheironomic

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon.js#208]
Since we are not working on this functionality for this release, it might be a good idea to comment out all the cheironomic code and adda paragraph in the "For Developers" page in the wiki explaining the progress that's been made so far.

**Comment by fujinaga** [comment]
Yes, you can comment this out.

**Comment by zoemcl** [comment]
Since we made squarenote the default page, the user has no way to access the cheironomic editing page.
