### ISSUE TITLE
Episemata: CUD

### ISSUE THREAD

**Issue by gburlet** [DDMAL/Neon.js#42]
Create:
- Client: add episema (horizontal, vertical) line to a neume (when neumified, combine contiguous episemata).
- Server: add `<episema>` tag to the MEI document

Update (Type):
- Client: toggle for horizontal or vertical episema
- Server: update `<episema>` tag in the MEI document

Delete:
- Client: remove episema glyph from the drawing surface
- Server: remove `<episema>` tag in the MEI document

**Comment by zoemcl** [comment]
Mostly implemented but still needs work. Refer to #145 and #146.
