### ISSUE TITLE
Wanted in Neon: Insert clef, rerun pitch finding on that staff

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/Neon.js#86]
Please see original issue: https://github.com/DDMAL/Rodan/issues/265

**Comment by ATranimal** [comment]
This is fixed in 6071506a2cbffe5097f049b01cb0d2301d1341e7.

If when Neon initially loads there is no clef on a line, none of the neumes on that line will show. Now that when we insert a clef, all the neumes that are there will be rendered on refresh.
