### ISSUE TITLE
Incorrect behaviour from build.sh when building the server

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon.js#99]
The closure compiler.jar file is no longer named compiler.jar by default when downloaded from the google server, so it will give a compiler.jar not found error.

In addition, some mac machines do not have 'wget' by default, perhaps look into replacing it with curl

**Comment by ahankinson** [comment]
@ATranimal could you add your full name to your GitHub profile? It's easier to know who's doing what then.

**Comment by ATranimal** [comment]
Fixed in commit https://github.com/DDMAL/Neon.js/commit/80285ca860c9804de7961f08b6bfff9c07eca6d9

**Comment by ATranimal** [comment]
@ahankinson sure, I'll do that
